Freezing
slhck/bufferer pull request #7
Opened 2021-05-11 08:05 UTC by davidlindero

2021-05-11 19:10 UTC, slhck requested changes

2021-05-11 19:10 UTC, slhck commented on bufferer/__main__.py
> +        self.input_duration = input_duration_pattern.search(output).group(1)
This might return no result. Should we exit in that case (like above) or show a warning?

2021-05-11 19:10 UTC, slhck commented on bufferer/__main__.py
> +            self.input_duration,
This seems odd. This means the output will always be as long as the input? To me it seems that this should not be there.

2021-05-12 08:26 UTC, davidlindero commented on bufferer/__main__.py
> +        self.input_duration = input_duration_pattern.search(output).group(1)
Sure, did a similar test as for has_audio and has_video. It will warn now if it cannot be parsed, as part of fps, resolution etc.

2021-05-12 08:28 UTC, davidlindero commented on bufferer/__main__.py
> +            self.input_duration,
This has been replaced with using input-duration for skipping, and None for traditional buffering. Also, if -t is set when calling bufferer, that -t is used instead (assuming this is always shorter than the source duration, which should make sense)

2021-05-12 08:57 UTC, slhck approved these changes

2021-05-12 09:15 UTC, merged